name: .NET

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: dotnet publish -c Release -r win-x64 --self-contained true -o ./publish

      - name: Set versioned ZIP name
        id: vars
        run: echo "ZIP_NAME=TUFFLauncher-v${{ github.ref_name }}.zip" >> $GITHUB_ENV

      - name: Zip published output
        run: zip -r ${{ env.ZIP_NAME }} ./publish

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ github.ref_name }}"
          name: "${{ github.ref_name }}"
          files: ${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.TUFFTECH_TOKEN }}
